  
name: Mirror to Bitbucket Repo via SSH

on: [ push, delete, create ]

jobs:
  git-mirror:
    runs-on: ubuntu-latest
    steps:
      - uses: wearerequired/git-mirror-action@v1.0.1
        env:
          SSH_PRIVATE_KEY: ${{ secrets.PRIVATE_SSH_KEY_FOR_MIRRORING }}
        with:
          source-repo: 'git@github.com:emitapp/emit-server.git'
          destination-repo: 'git@bitbucket.org:emitapp/server-mirror.git'
